# Generated by Django 5.1.4 on 2025-03-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text="Font Awesome icon class, e.g., 'fas fa-truck'", max_length=100)),
                ('delay', models.IntegerField(default=200, help_text='AOS animation delay in milliseconds')),
            ],
        ),
    ]
