# Generated by Django 5.1.4 on 2025-03-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Vitamins', 'Vitamins'), ('Pain Relief', 'Pain Relief'), ('First Aid', 'First Aid'), ('Skin Care', 'Skin Care')], max_length=50)),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rating', models.FloatField()),
                ('reviews_count', models.IntegerField()),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('delay', models.IntegerField(default=100)),
            ],
        ),
    ]
