# Generated by Django 5.1.4 on 2025-03-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_site', '0004_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='why_us/')),
            ],
        ),
    ]
