# Generated by Django 5.1.4 on 2025-03-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_site', '0005_whychooseusimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhyChooseUsImage',
        ),
    ]
