# Generated by Django 5.1.4 on 2025-03-23 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_site', '0006_delete_whychooseusimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroSection',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
