# Generated by Django 5.1.4 on 2025-03-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy_site', '0007_delete_herosection_delete_product_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Enter phone number with country code', max_length=20)),
                ('email', models.EmailField(help_text='Enter email address', max_length=254)),
                ('address', models.TextField(help_text='Enter complete address')),
                ('is_active', models.BooleanField(default=True, help_text='Set to True to display this contact info')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
    ]
