# Generated by Django 5.1.4 on 2025-03-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_site', '0010_remove_menuitem_parent_alter_menuitem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
