# Generated by Django 5.1.4 on 2025-03-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_site', '0011_alter_menulink_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading for the hero section', max_length=200)),
                ('subtitle', models.TextField(help_text='Subtext below the main heading')),
                ('button_text', models.CharField(default='Shop Now', help_text='Text to display on the button', max_length=50)),
                ('button_link', models.CharField(blank=True, help_text='URL for the button (optional)', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only one hero section can be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.AlterField(
            model_name='menulink',
            name='url',
            field=models.CharField(blank=True, default='#', max_length=200),
        ),
    ]
