# Generated by Django 5.1.4 on 2025-03-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_site', '0013_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Advertisement title', max_length=200)),
                ('description', models.TextField(help_text='Advertisement description')),
                ('image', models.ImageField(help_text='Advertisement image', upload_to='advertisements/')),
                ('button_text', models.CharField(default='Shop Now', help_text='Text to display on the button', max_length=50)),
                ('button_link', models.CharField(default='#', help_text='URL for the button', max_length=200)),
                ('is_main', models.BooleanField(default=False, help_text='Whether this is the main (large) advertisement')),
                ('order', models.IntegerField(default=0, help_text='Order of appearance for side advertisements')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this advertisement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-is_main', 'order'],
            },
        ),
    ]
