# Generated by Django 5.1.4 on 2025-03-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_site', '0015_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['order'], 'verbose_name': 'Advertisement', 'verbose_name_plural': 'Advertisements'},
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='is_main',
        ),
    ]
